baseURL = "https://wolfgang.gassler.org"
languageCode = "en-us"
title = "wolfgang gassler"
theme = "schafele"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

[permalinks]
  posts = "/:slug/"

[taxonomies]
  tag = "tags"

[author]
	name = "woolf"

[params]
	math = true

	description = "Website Description"

	linkedin = "https://www.linkedin.com/in/wolfganggassler/"
    github = "https://github.com/woolfg"
    constructeev = "https://www.constructeev.com/gassler-blog"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "about"
	url = "/about/"
	weight = 4 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

#[[menu.main]]
#	identifier = "books"
#	name = "good reads"
#	url = "/books/"
#	weight = 3

[[menu.main]]
	identifier = "consulting"
	name = "consulting"
	url = "/consulting/"
	weight = 3

[[menu.main]]
	identifier = "tags"
	name = "tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	name = "posts"
	identifier = "archives"
	url = "/archives/"
	weight = 1

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true